### PR TITLE
several mods compat

### PR DESCRIPTION
**Pull request by JieningYu**
- ae2(updated one)
- promenade
- alloy forgery(creative blaze cake is 96000 because it's deepslate forge's max fueltier.)
- mores
- unearthed
- universal ores
they all has fabric:load_conditions except alloy forgery fuels because it won't load without alloy forgery.

### CODE REVIEW

**Comment by JieningYu** [comment]
I only edited compat data.
A problem occurred configuring root project 'Create'.
> Could not resolve all files for configuration ':detachedConfiguration2'.
   > Could not find org.quiltmc:quilt-mappings:1.18.2+build.21.

**Comment by TropheusJ** [comment]
Ignore the build, mavens are funky right now

**Comment by JieningYu** [comment]
is create supported quilt?

**Comment by TropheusJ** [comment]
We use quilt mappings for docs and params. Latest commit fixed build.

**Comment by JieningYu** [comment]
> * ae2(updated one)
> * promenade
> * alloy forgery(creative blaze cake is 96000 because it's deepslate forge's max fueltier.)
> * mores
> * unearthed
> * universal ores
>   they all has fabric:load_conditions except alloy forgery fuels because it won't load without alloy forgery.

now with betternether and immersive weathering support

**Comment by JieningYu** [comment]
？

**Comment by JieningYu** [comment]
hi?

**Comment by AlphaMode** [comment]
your pr is modifying content from the forge version and I don't think it will be accepted unless you reverse it

**Comment by JieningYu** [comment]
ok

**Comment by JieningYu** [comment]
no modifies now

**Comment by JieningYu** [comment]
now with:

- architects_palette
- croptopia
- ecologics
- techreborn
- mythicmetals
- alloygery

**Comment by TropheusJ** [comment]
Will try to review this today

**Comment by StockiesLad** [comment]
Ok to be clear im not asking u to do any of these, this is just for everybody to get some insight:

Create (crushing) still doesn't process ores from:

modern industrialisation
Mythic metals (idk why????)
Better end (it isn't working?)
Excavated Variants (this uses JSON's so it would be easier)
Industrial revolution
paradise lost
space dimensions (agape space)

Side thing: since this is create plus, electricity compat?


EDIT: thank you JieningYu for your help!

**Comment by TropheusJ** [comment]
A lot of these would likely be fixed by tags, which we’re looking into.

**Comment by StockiesLad** [comment]
> A lot of these would likely be fixed by tags, which we’re looking into.

Fair enough. You guys are doing F*&*ing great! Like there are no word. Just thank you guys for all the work you are putting into this. Getting bugs fixed in literal hours. Fantastic job! Keep it up.

**Comment by JieningYu** [comment]
> Ok to be clear im not asking u to do any of these, this is just for everybody to get some insight:
> 
> 
> 
> Create (crushing) still doesn't process ores from:
> 
> 
> 
> modern industrialisation
> 
> Mythic metals (idk why????)
> 
> Better end (it isn't working?)
> 
> Excavated Variants (this uses JSON's so it would be easier)
> 
> Industrial revolution
> 
> paradise lost
> 
> space dimensions (agape space)
> 
> 
> 
> Side thing: since this is create plus, electricity compat?
> 
> 
> 
> 
> 
> EDIT: thank you JieningYu for your help!

This PR is not CreatePlus.
If you want Mythic Metals compat, use the original CreatePlus mod/datapack(datapack dosen't include custom crushed ors feature)

modern industrialisation and paradise lost is planned but agape space and Industrial revolution not
Will support mods that requires bclib when quilted fabric api is out of beta.

**Comment by StockiesLad** [comment]
> > Ok to be clear im not asking u to do any of these, this is just for everybody to get some insight:
> > Create (crushing) still doesn't process ores from:
> > modern industrialisation
> > Mythic metals (idk why????)
> > Better end (it isn't working?)
> > Excavated Variants (this uses JSON's so it would be easier)
> > Industrial revolution
> > paradise lost
> > space dimensions (agape space)
> > Side thing: since this is create plus, electricity compat?
> > EDIT: thank you JieningYu for your help!
> 
> This PR is not CreatePlus. If you want Mythic Metals compat, use the original CreatePlus mod/datapack(datapack dosen't include custom crushed ors feature)
> 
> modern industrialisation and paradise lost is planned but agape space and Industrial revolution not Will support mods that requires bclib when quilted fabric api is out of beta.

One question, why support quilt when supporting fabric is supporting 2 loaders simultaneously
EDIT: and btw Thank you for the input!

**Comment by JieningYu** [comment]
> 



> > > Ok to be clear im not asking u to do any of these, this is just for everybody to get some insight:
> > > Create (crushing) still doesn't process ores from:
> > > modern industrialisation
> > > Mythic metals (idk why????)
> > > Better end (it isn't working?)
> > > Excavated Variants (this uses JSON's so it would be easier)
> > > Industrial revolution
> > > paradise lost
> > > space dimensions (agape space)
> > > Side thing: since this is create plus, electricity compat?
> > > EDIT: thank you JieningYu for your help!
> > 
> > 
> > This PR is not CreatePlus. If you want Mythic Metals compat, use the original CreatePlus mod/datapack(datapack dosen't include custom crushed ors feature)
> > modern industrialisation and paradise lost is planned but agape space and Industrial revolution not Will support mods that requires bclib when quilted fabric api is out of beta.
> 
> One question, why support quilt when supporting fabric is supporting 2 loaders simultaneously EDIT: and btw Thank you for the input!

to allure more players to use Quilt

**Comment by StockiesLad** [comment]
Quilt is essentially just another fork of fabric that really doesn't have more then fabric (as of now).
Switching modloaders is a mere inconvenience, there is nothing special about quilt aside from it being just another modloader...

**Comment by JieningYu** [comment]
> Quilt is essentially just another fork of fabric that really doesn't have more then fabric (as of now). Switching modloaders is a mere inconvenience, there is nothing special about quilt aside from it being just another modloader...

Quilt has QSL and more features compared with Fabric.

**Comment by StockiesLad** [comment]
> > Quilt is essentially just another fork of fabric that really doesn't have more then fabric (as of now). Switching modloaders is a mere inconvenience, there is nothing special about quilt aside from it being just another modloader...
> 
> Quilt has QSL and more features compared with Fabric.

and disproportionately more bugs.

**Comment by maximumpower55** [comment]
> > > Quilt is essentially just another fork of fabric that really doesn't have more then fabric (as of now). Switching modloaders is a mere inconvenience, there is nothing special about quilt aside from it being just another modloader...
> > 
> > 
> > Quilt has QSL and more features compared with Fabric.
> 
> and disproportionately more bugs.

Its still in beta :/

**Comment by StockiesLad** [comment]
> > > > Quilt is essentially just another fork of fabric that really doesn't have more then fabric (as of now). Switching modloaders is a mere inconvenience, there is nothing special about quilt aside from it being just another modloader...
> > > 
> > > 
> > > Quilt has QSL and more features compared with Fabric.
> > 
> > 
> > and disproportionately more bugs.
> 
> Its still in beta :/

Indeed! Time will tell how effective quilt is.

**Comment by JieningYu** [comment]
i give up this pr.
check createplus if you want better compat.

**Comment by StockiesLad** [comment]
I'm gonna wait for the tag fix by them.

**Comment by StockiesLad** [comment]
Bc quilt is too glitchy to use
just crashing all the time

**Comment by StockiesLad** [comment]
LambdAuora I'm just waiting for u to dislike this too lmao.

**Comment by JieningYu** [comment]
> Bc quilt is too glitchy to use just crashing all the time

a create+ datapack for fabric exists

**Comment by JieningYu** [comment]
https://github.com/JieningYu/CreatePlus/archive/refs/heads/datapack/fabric/1.18.2.zip

**Comment by StockiesLad** [comment]
Thank you for the direct link!

**Comment by JieningYu** [comment]
unarchive zhe zip before using

**Comment by maximumpower55** [comment]
> Bc quilt is too glitchy to use just crashing all the time

Instead of Whining about it, how about you actually report the crash :/

**Comment by StockiesLad** [comment]
> unarchive zhe zip before using

👍

**Comment by StockiesLad** [comment]
> > Bc quilt is too glitchy to use just crashing all the time
> 
> Instead of Whining about it, how about you actually report the crash :/

Nah, how about I don't.

**Pull request closed without merging**
