### PR TITLE
Load create's datapack

### PR DESCRIPTION
**Pull request by AlphaMode**
Loads creates datapack

### CODE REVIEW

**Review by Platymemo — CHANGES_REQUESTED** [review]
See the [Tag Conventions](https://fabricmc.net/wiki/tutorial:tags). Most of the common namespace tags are formatted incorrectly. Also, the TagUtil class in the create lib needs to be changed to include all the correct namespaces. I know most/all of the formatting problems were inherited since you copied them over from src/generated/ but the reason they're there is that they're unfinished.

**Comment by AlphaMode** [comment]
> See the [Tag Conventions](https://fabricmc.net/wiki/tutorial:tags). Most of the common namespace tags are formatted incorrectly. Also, the TagUtil class in the create lib needs to be changed to include all the correct namespaces. I know most/all of the formatting problems were inherited since you copied them over from src/generated/ but the reason they're there is that they're unfinished.

Got it working on the changes now

**Comment by AlphaMode** [comment]
> > See the [Tag Conventions](https://fabricmc.net/wiki/tutorial:tags). Most of the common namespace tags are formatted incorrectly. Also, the TagUtil class in the create lib needs to be changed to include all the correct namespaces. I know most/all of the formatting problems were inherited since you copied them over from src/generated/ but the reason they're there is that they're unfinished.
> 
> Got it working on the changes now

switched over to proper common tags now all I need to do is update the recipes and etc to use them

**Comment by Platymemo** [comment]
Awesome, I pushed the updated TagUtil class to have all the right namespaces now so you don't have to add that to this PR

**Pull request closed without merging**
