### PR TITLE
0.5.1 Patch F Port 1.20

### PR DESCRIPTION
**Pull request by IThundxr**

### CODE REVIEW

**Comment by AwesomeDude091** [comment]
Does this include the flywheel patch?

**Comment by IThundxr** [comment]
> Does this include the flywheel patch?

At the moment no, however I'll be switching to IMS's flywheel branches and pulling builds from my maven until they are able to be merged into flywheel main & put on the maven

**Comment by IThundxr** [comment]
This PR is currently blocked as @IMS212 's flywheel fork crashes alongside sodium

**Comment by Tymonoman** [comment]
> This PR is currently blocked as @IMS212 's flywheel fork crashes alongside sodium

Does this mean everyone is waiting for him?

**Comment by IThundxr** [comment]
> > This PR is currently blocked as @IMS212 's flywheel fork crashes alongside sodium
> 
> Does this mean everyone is waiting for him?

no its just that its one of the problems in this alongside portal trains not working at all, this PR will take a lil bit to get merged since a few bugs need ironing out

**Comment by Tymonoman** [comment]
> > > This PR is currently blocked as @IMS212 's flywheel fork crashes alongside sodium
> > 
> > 
> > Does this mean everyone is waiting for him?
> 
> no its just that its one of the problems in this alongside portal trains not working at all, this PR will take a lil bit to get merged since a few bugs need ironing out

So how much longer you think we will be waiting for the patch that works with sodium 5.2?

**Comment by IThundxr** [comment]
> > > > This PR is currently blocked as @IMS212 's flywheel fork crashes alongside sodium
> > > 
> > > 
> > > Does this mean everyone is waiting for him?
> > 
> > 
> > no its just that its one of the problems in this alongside portal trains not working at all, this PR will take a lil bit to get merged since a few bugs need ironing out
> 
> So how much longer you think we will be waiting for the patch that works with sodium 5.2?

Not sure I don't gives any ETAs

**Comment by AwesomeDude091** [comment]
I assume Sodium is not patched yet?

**Comment by IThundxr** [comment]
> I assume Sodium is not patched yet?

It is however we are waiting on pepper to make a proper flywheel fabric release and then this can be merged & any bugs left (I haven't seen any) can be fixed

**Comment by AwesomeDude091** [comment]
GO Pepper :)

**Comment by IThundxr** [comment]
https://github.com/Jozufozu/Flywheel/pull/214 needs to be merged before this can properly be finished

**Review by Lisoveliy — APPROVED** [review]

**Comment by IThundxr** [comment]
- Todo: make sure AllCreativeTabs.java looks like https://github.com/Creators-of-Create/Create/blob/mc1.20.1/dev/src/main/java/com/simibubi/create/AllCreativeModeTabs.java alongside https://github.com/Layers-of-Railways/Railway/blob/1.20/dev/fabric/src/main/java/com/railwayteam/railways/registry/fabric/CRCreativeModeTabsImpl.java

**Comment by Giovanniricotta2002** [comment]
When will the pull request be validated?

**Comment by IThundxr** [comment]
> When will the pull request be validated?

As said multiple times, it needs the flywheel pr merged first, then needs to be tested & reviewed and then porting lib has to be bumped after the deployer crash is fixed then it can be merged & released so just be patient for now

**Comment by Giovanniricotta2002** [comment]
ok

**Comment by Giovanniricotta2002** [comment]
I ask the question here (since for me it is in continuity) but for the **AllRecipeTypes** enum it is not passed under public class like for the fan processes

**Comment by IThundxr** [comment]
> I ask the question here (since for me it is in continuity) but for the **AllRecipeTypes** enum it is not passed under public class like for the fan processes

https://github.com/IThundxr-Modding/Create-Fabric/blob/mc1.20.1/fabric/dev/src/main/java/com/simibubi/create/AllRecipeTypes.java its already a public enum?

**Comment by Giovanniricotta2002** [comment]
>    >I ask the question here (since for me it is in continuity) but for the AllRecipeTypes enum it is not passed under public class like for the fan processes
>
>https://github.com/IThundxr-Modding/Create-Fabric/blob/mc1.20.1/fabric/dev/src/main/java/com/simibubi/create/AllRecipeTypes.java its already a public enum?

I didn't know you could extend an enum, sorry for the inconvenience

**Comment by unilock** [comment]
Out of curiosity, why was https://github.com/IThundxr-Modding/Create-Fabric/commit/75ffe5b00797f576d3c4f2bfc088dc02ccce6788 reverted?  
(Porting Lib's FakePlayer impl was [replaced by Fabric API's](https://github.com/Fabricators-of-Create/Porting-Lib/commit/a238316d0f4df68e507bc7907aba832f55072b65), btw)

**Comment by IThundxr** [comment]
> Out of curiosity, why was [IThundxr-Modding@75ffe5b](https://github.com/IThundxr-Modding/Create-Fabric/commit/75ffe5b00797f576d3c4f2bfc088dc02ccce6788) reverted? (Porting Lib's FakePlayer impl was [replaced by Fabric API's](https://github.com/Fabricators-of-Create/Porting-Lib/commit/a238316d0f4df68e507bc7907aba832f55072b65), btw)

it uh, made every obj model fail to load, contraptions fail to render and made items using obj models to stop rendering :ioa:

**Pull request merged**
