### PR TITLE
Update porting lib from legacy to new 1.20.1 branch

### PR DESCRIPTION
**Pull request by IThundxr**

### CODE REVIEW

**Comment by IThundxr** [comment]
Current Issues:
- Obj loading doesnt work at all
- MultiRenderTypeModel's dont work

**Comment by AlphaMode** [comment]
Its because "porting_lib:loader": "porting_lib:obj" needs to be changed to "loader": "porting_lib:obj",

**Comment by TropheusJ** [comment]
That change should not be made, support for the new field should be re-added to porting lib

**Comment by AlphaMode** [comment]
I'm wondering if there will be any issues related to fake players

**Comment by IThundxr** [comment]
> I'm wondering if there will be any issues related to fake players

should be fine, the porting lib -> fapi fake player change was pretty seamless, but testing should be done anyway

**Comment by IThundxr** [comment]
The run can be ran again and then this can be tested/merged

main things to test are fake players & deployers killing mobs

**Comment by TropheusJ** [comment]
Thanks for handling this

**Pull request merged**
