### PR TITLE
Add null-safety check on usage of BlockEntity.loadStatic

### PR DESCRIPTION
**Pull request by TurnrDev**
We had a schematicannon crash our server the other day, followed the logs, brought me here. Here we go. Happy to rebase for 1.18 and 1.20 too, as well as happy to upstream to forge versions if affected. lmk

### CODE REVIEW

**Comment by IThundxr** [comment]
Could you send the crash log?

**Comment by TurnrDev** [comment]
[crash-2024-02-27_18.06.08-server.txt](https://github.com/Fabricators-of-Create/Create/files/14438318/crash-2024-02-27_18.06.08-server.txt)

**Comment by TurnrDev** [comment]
TL;DR: BlockEntity.loadStatic can return a null value, but we weren't checking for nulls

**Comment by goteusz-maszyk** [comment]
Seems like a very common-loader thing...

**Comment by TropheusJ** [comment]
Please send the regular log too (latest.log).
This fix should target forge 1.18.

**Pull request closed without merging**
