### PR TITLE
switch forge config maven to fuzs maven

### PR DESCRIPTION
**Pull request by rhysdh540**
oh boy do I love having source jars

oh yeah I also changed quiltflower to vineflower lol idk why I did this like last week

### CODE REVIEW

**Comment by mucookul** [comment]
Quiltflower separated from Quilt and renamed themselves to Vineflower

**Comment by rhysdh540** [comment]
no yes I know that I just don't remember why I included it with this pr

**Comment by rhysdh540** [comment]
also note that the api has different coords for 1.19+ (`fuzs.forgeconfigapiport`)

**Comment by TropheusJ** [comment]
thanks

**Pull request merged**
