### PR TITLE
Fabric 1.19.2 port

### PR DESCRIPTION
**Pull request by alula**

### CODE REVIEW

**Comment by 0x6273** [comment]
Worldgen still seems broken in this pr. No zinc is generating.

**Comment by alula** [comment]
I'll fix that soon, thanks for letting me know

**Comment by KernelFreeze** [comment]
I tried it and it works pretty well, but it crashes on server

```
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.simibubi.create.foundation.data.CreateRegistrate.lambda$virtualFluid$6(CreateRegistrate.java:171) ~[create-fabric-1.19.2-0.5.0f.jar:?]
        at com.tterrag.registrate.AbstractRegistrate.entry(AbstractRegistrate.java:685) ~[registrate-fabric-1.1.6-MC1.19.2-c88a67feea36d1a3.jar:?]
        at com.simibubi.create.foundation.data.CreateRegistrate.virtualFluid(CreateRegistrate.java:170) ~[create-fabric-1.19.2-0.5.0f.jar:?]
        at com.simibubi.create.AllFluids.<clinit>(AllFluids.java:56) ~[create-fabric-1.19.2-0.5.0f.jar:?]
        at com.simibubi.create.Create.onInitialize(Create.java:87) ~[create-fabric-1.19.2-0.5.0f.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
        ... 7 mor
```

**Comment by AlphaMode** [comment]
Thanks for the PR I'll get to fixing the last of the minor issues!

**Pull request merged**
