### PR TITLE
Fix world generation

### PR DESCRIPTION
**Pull request by RedBoxing**
Fix world generation

### CODE REVIEW

**Comment by TropheusJ** [comment]
Does this let Create worldgen happen as well, or just fix vanilla worldgen?

**Comment by RedBoxing** [comment]
both

**Comment by TropheusJ** [comment]
Unfortunate timing, we actually have worldgen working already, just not public yet, done by @AlphaMode. We’re going to use what we have instead as it uses FAPI for generation. Thank you for the contribution though!

**Comment by RedBoxing** [comment]
I made the fix with FAPI but removed it before doing the pull request

**Pull request closed without merging**
