### PR TITLE
Fixed Depot rendering issues

### PR DESCRIPTION
**Pull request by IGN-Styly**
in this Commit i changed the DepotRenderer  to add a setting named BlockItemAsItem so it renders BlockItems such as the wrench in #977, this setting fixes this issue, there probably are more blocks which have this issue but have not found more.

### CODE REVIEW

**Comment by PepperCode1** [comment]
As you are likely aware, the issue is that some items render sideways on belts and depots. This happens because the model's transformation for the transform mode that belts and depots use (`FIXED`) rotates the item. This mode is usually used for item frames. Not all items apply a 90° rotation though, so just undoing the rotation won't work.

I have attempted to fix this bug before. I tried changing the transform mode to `GROUND`, which fixed the rotation, but caused other issues. Another possible solution would be to remove all rotation found in the model's transformation, but this could be difficult or impossible to detect reliably. Alternatively, it is possible to use a tag to unrotate specific items. However, I do not like any of these solutions.

Your solution uses the `blockItem` boolean (whether the model is "3D"). This is not reliable and thus is no better than any of the previously mentioned solutions. These changes also allow the fix to be disabled, which should not be possible (if the fix is unreliable enough that it needs the ability to be disabled, then it is a bad fix). If you find a solution that is actually reliable, you can let me know. I can commit a good solution directly to the Forge version of Create.

**Comment by IGN-Styly** [comment]
I have not found other issues, if you read the code in the commit you will see I am just rotating the item by 90 degrees.

**Comment by IGN-Styly** [comment]
And added a setting for it, should we try doing it like item frames.

**Comment by IGN-Styly** [comment]
You see if it's a blockItem it does not rotate by 90 degrees, I made so if a setting is enabled it rotates it by 90 degrees.

**Pull request closed without merging**
